name: Go API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: librarymanagementsystem_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.22.2"

      - name: Install golang-migrate
        run: |
          go get -u -d github.com/golang-migrate/migrate/v4/cmd/migrate
           cd $GOPATH/pkg/mod/github.com/golang-migrate/migrate/v4/cmd/migrate
           go build -tags 'postgres' -ldflags="-X main.Version=$(git describe --tags)" -o $GOPATH/bin/migrate .

      - name: Start PostgreSQL and wait for connection
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          until nc -z localhost 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Run database migrations
        run: |
          migrate -database "postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/librarymanagementsystem_test?sslmode=disable" -path migrations/ up

      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
