name: Go API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: librarymanagementsystem_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.22.2"

      - name: Install dependencies
        run: go mod download

      - name: Start PostgreSQL and wait for connection
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          until nc -z localhost 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/
          which migrate

      - name: Run database migrations
        run: |
          echo "package main\n\nimport _ \"github.com/golang-migrate/migrate/v4/database/postgres\"" > dummy.go
          go mod tidy
          migrate -database "postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/librarymanagementsystem_test?sslmode=disable" -path migrations/ up

      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
